### PR TITLE
Removed the extremely damaged Staffers page

### PR DESCRIPTION
**Pull request by jmdawson**
IT works terribly, five people told me to take it out.

### CODE REVIEW

**Comment by kitsuta** [comment]
Haha, so as a longer explanation (since most of this discussion is buried in MAGFest Slack):

Dawson and other folks on MAGFest's security team have been navigating to the Staffers page to look up staffers' details for various tasks. This page has had a lot of extra stuff tacked onto it that's special-case use for MAGFest's STOPS department, so partly for that reason, it is a very inefficient and slow-loading page.

The quick fix here is to straight-up just remove the link from the main dropdown, so unwitting admins don't accidentally try to use it for simple tasks (like looking up a staffer, which is better done through People > Attendees). A longer-term fix is to intelligently break up the staffing page so that complex reports don't bring the page load to a screeching halt when someone just wants to quickly grab a staffer's details.

**Comment by kitsuta** [comment]
Also, +1

**Comment by earl7399** [comment]
+1

## 

Robert Earl r.a.earl@gmail.com
FAX: 1-440-919-5086

**Comment by kitsuta** [comment]
This was actually later done in the MAGFest repo, plus the page was dramatically improved, so I'm closing this PR. Thank you for submitting it.

**Pull request closed without merging**
